--------------------------------------------------------
-- Archivo creado  - domingo-enero-29-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View GPYV_007_PARTICIPANTE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "GESTOR"."GPYV_007_PARTICIPANTE" ("A051CODIGO", "A05IDPROYECTO", "A051IDPERSONA", "A052NUMRDOCMNT", "A052NOMBRE", "A052APELLIDO", "A015CODIGO", "A052TIPDOCMNT", "A051RESPONSABILIDAD", "A051ESTADOREGISTRO") AS 
  SELECT A051CODIGO,
    A05IDPROYECTO,
    A051IDPERSONA,
    A052NUMRDOCMNT,
    A052NOMBRE,
    A052APELLIDO,
    A015CODIGO,
    A015DESCRPCNTIPDOCMNT,
    A051RESPONSABILIDAD,
    A051ESTADOREGISTRO
  FROM GPYT_T051_PARTICIPANTE PART
  LEFT JOIN GPYT_T052_PERSONA PERS ON PART.A051IDPERSONA = PERS.A052CODIGO
  LEFT JOIN GPYT_T015_TIPO_DOCUMENTO TIP ON PERS.A052TIPDOCMNT = TIP.A015CODIGO;
REM INSERTING into GESTOR.GPYV_007_PARTICIPANTE
SET DEFINE OFF;