DELETE FROM GPYT_T022_TIPO_ACTIVIDAD;

-- MDL / Fuente
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (1, 'Realizar inversiones en obras de salud, educación, saneamiento básico, agua potable, preservación del medio ambiente, vivienda de interés social y/o creación de microempresa', 14, 30, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (2, 'Promover la participación laboral de personas provenientes de las comunidades locales en las actividades del proyecto', 14, 30, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (3, 'Realizar programas de capacitación, entrenamiento o educación para los trabajadores provenientes de las comunidades con el fin de mejorar sus habilidades y destrezas para cumplir adecuadamente con sus funciones dentro de la operación del proyecto', 14, 30, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (4, 'Emplear sistemas productivos (equipamiento, tecnologías y procesos, A022USUARIOCREACION) más limpios y/o eficientes que minimizan el uso de recursos y el impacto ambiental', 14, 30, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (5, 'Realizar programa de transferencia y apropiación de tecnología o conocimientos de proceso', 14, 30, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (6, 'Generar impactos ambientales positivos adicionales a la contribución de la reducción del calentamiento global', 14, 30, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (7, 'Adelantar medida de adaptación, gestión del riesgo y/o reducción de la vulnerabilidad a los efectos adversos del cambio climático', 14, 30, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (8, 'Realizar actividades de reducción de emisiones', 14, 30, 'S', 'A', sysdate, 0);

-- MDL / Sumidero
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (9, 'Realizar inversiones en obras de salud, educación, saneamiento básico, agua potable, preservación del medio ambiente, vivienda de interés social y/o creación de microempresa', 14, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (10, 'Promover la participación laboral de personas provenientes de las comunidades locales en las actividades del proyecto', 14, 31, 'N', 'A', sysdate, 0);     
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (11, 'Realizar programas de capacitación, entrenamiento o educación para los trabajadores provenientes de las comunidades con el fin de mejorar sus habilidades y destrezas para cumplir adecuadamente con sus funciones dentro de la operación del proyecto', 14, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (12, 'Emplear sistemas productivos (equipamiento, tecnologías y procesos, A022USUARIOCREACION) más limpios y/o eficientes que minimizan el uso de recursos y el impacto ambiental', 14, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (13, 'Realizar un programa de transferencia y apropiación de tecnología o conocimientos de proceso', 14, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (14, '¿Generar impactos ambientales positivos adicionales a la contribución de la reducción del calentamiento global?', 14, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (15, '¿Utilizar especies nativas? ¿En qué porcentaje?', 14, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (16, 'Adelantar medida de adaptación, gestión del riesgo y/o reducción de la vulnerabilidad a los efectos adversos del cambio climático', 14, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (17, 'Actividad de remoción de emisiones GEI del proyecto MDL', 14, 31, 'S', 'A', sysdate, 0);

-- MLDPoA / Fuente
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (18, '¿El programa realizará inversiones en obras de salud, educación, saneamiento básico, agua potable, preservación del medio ambiente, vivienda de interés social y/o creación de microempresa?', 15, 30, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (19, '¿El programa da prioridad a la participación laboral de personas provenientes de las comunidades locales en las actividades del proyecto?', 15, 30, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (20, '¿El programa prevé programas de capacitación, entrenamiento o educación para los trabajadores provenientes de las comunidades con el fin de mejorar sus habilidades y destrezas para cumplir adecuadamente con sus funciones dentro de la operación del proyecto?', 15, 30, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (21, '¿El programa emplea sistemas productivos (equipamiento, tecnologías y procesos, A022USUARIOCREACION) más limpios y/o eficientes que minimizan el uso de recursos y el impacto ambiental?', 15, 30, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (22, '¿El programa presenta un programa de transferencia y apropiación de tecnología o conocimientos de proceso?', 15, 30, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (23, '¿El programa genera impactos ambientales positivos adicionales a la contribución de la reducción del calentamiento global?', 15, 30, 'N', 'A', sysdate, 0);                          
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (24, '¿El programa prevé alguna medida de adaptación, gestión del riesgo y/o reducción de la vulnerabilidad a los efectos adversos del cambio climático?', 15, 30, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (25, 'Actividades de reducción', 15, 30, 'S', 'A', sysdate, 0);

-- MDLPoA / Sumidero
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (26, 'Realizar actividades de conservación o restauración ecológica. ¿En qué consisten estas actividades y en qué tipo de ecosistemas?', 15, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (27, 'Realizar inversiones en obras de salud, educación, saneamiento básico, agua potable, preservación del medio ambiente, vivienda de interés social y/o creación de microempresa?', 15, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (28, '¿Promover la participación laboral de personas provenientes de las comunidades locales en las actividades del proyecto?', 15, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (29, '¿Realizar programas de capacitación, entrenamiento o educación para los trabajadores provenientes de las comunidades con el fin de mejorar sus habilidades y destrezas para cumplir adecuadamente con sus funciones dentro de la operación del proyecto?', 15, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (30, '¿Utilizar especies nativas? ¿En qué Porcentaje?', 15, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (31, 'Emplear sistemas productivos (equipamiento, tecnologías y procesos, A022USUARIOCREACION) más limpios y/o eficientes que minimizan el uso de recursos y el impacto ambiental?', 15, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (32, '¿Realizar un programa de transferencia y apropiación de tecnología o conocimientos de proceso?', 15, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (33, '¿Generar impactos ambientales positivos adicionales a la contribución de la reducción del calentamiento global?', 15, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (34, 'Adelantar medida de adaptación, gestión del riesgo y/o reducción de la vulnerabilidad a los efectos adversos del cambio climático?', 15, 31, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (35, 'Actividades de remoción', 15, 31, 'S', 'A', sysdate, 0);

-- NAMA 
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (36, 'Realizar actividades asociadas a beneficios ambientales', 12, NULL, 'N', 'A', sysdate, 0);  
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (37, 'Realzar actividades asociadas a beneficios sociales', 12, NULL, 'N', 'A', sysdate, 0);  
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (38, 'Realizar actividades asociadas a beneficios económicos', 12, NULL, 'N', 'A', sysdate, 0);  
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (39, 'Realizar actividades asociadas a beneficios en adaptación al Cambio climático', 12, NULL, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (40, 'Realizar actividades de reducción de emisiones GEI', 12, NULL, 'S', 'A', sysdate, 0);

-- PDBCrc
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (41, 'Realizar actividades asociadas a beneficios ambientales', 13, NULL, 'N', 'A', sysdate, 0);  
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (42, 'Realzar actividades asociadas a beneficios sociales', 13, NULL, 'N', 'A', sysdate, 0);  
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (43, 'Realizar actividades asociadas a beneficios económicos', 13, NULL, 'N', 'A', sysdate, 0);  
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (44, 'Realizar actividades asociadas a beneficios en adaptación al Cambio climático', 13, NULL, 'N', 'A', sysdate, 0);
INSERT INTO GPYT_T022_TIPO_ACTIVIDAD (A022CODIGO, A022DESCRPCNACTVDD, A022IDTIPPROYCT, A022IDTIPPROYCTMDL, A022ACTESPECIAL, A022ESTADOREGISTRO, A022FECHACREACION, A022USUARIOCREACION) 
VALUES (45, 'Realizar actividades de reducción de emisiones GEI', 13, NULL, 'S', 'A', sysdate, 0);

COMMIT;