DELETE FROM GPYT_T025_ADJUNTO;

INSERT INTO GPYT_T025_ADJUNTO (A025CODIGO, A025NOMBRADJNT, A025DESCRPCNADJNT, A025IDTIPPROYCT, A025IDPANTALLA, A025APLICPCNADJNT, A025NOMFORMATO, A025ESTADOREGISTRO,  A025FECHACREACION, A025USUARIOCREACION) 
VALUES (1, 'Solicitud de Consideracion Temprana', 'No. De radicado de la solicitud de Consideración Temprana del proyecto MDL suscrita por el representante legal o quien haga sus veces (en caso de ser persona jurídica) o la persona natural interesada, con el nombre o razón social, número de identificación, domicilio y nacionalidad. Esto en caso de que este ya haya sido entregado al Ministerio de Ambiente y Desarrollo Sostenible)', 14, 7, 'SI', NULL, 'A', sysdate, 0);
INSERT INTO GPYT_T025_ADJUNTO (A025CODIGO, A025NOMBRADJNT, A025DESCRPCNADJNT, A025IDTIPPROYCT, A025IDPANTALLA, A025APLICPCNADJNT, A025NOMFORMATO, A025ESTADOREGISTRO,  A025FECHACREACION, A025USUARIOCREACION) 
VALUES (2, 'Solicitud de Consideracion Temprana', 'No. De radicado de la solicitud de Consideración Temprana del proyecto MDL suscrita por el representante legal o quien haga sus veces (en caso de ser persona jurídica) o la persona natural interesada, con el nombre o razón social, número de identificación, domicilio y nacionalidad. Esto en caso de que este ya haya sido entregado al Ministerio de Ambiente y Desarrollo Sostenible)', 15, 7, 'SI', NULL, 'A', sysdate, 0);
INSERT INTO GPYT_T025_ADJUNTO (A025CODIGO, A025NOMBRADJNT, A025DESCRPCNADJNT, A025IDTIPPROYCT, A025IDPANTALLA, A025APLICPCNADJNT, A025NOMFORMATO, A025ESTADOREGISTRO,  A025FECHACREACION, A025USUARIOCREACION) 
VALUES (3, 'Formato F-CDM-PC Form de Prior Consideration de la CMNUCC', NULL, 14, 7, 'NO', 'F-CDM-PC', 'A', sysdate, 0);
INSERT INTO GPYT_T025_ADJUNTO (A025CODIGO, A025NOMBRADJNT, A025DESCRPCNADJNT, A025IDTIPPROYCT, A025IDPANTALLA, A025APLICPCNADJNT, A025NOMFORMATO, A025ESTADOREGISTRO,  A025FECHACREACION, A025USUARIOCREACION) 
VALUES (4, 'Formato CDM-POA-PC-Form de Prior Consideration de la CMNUCC', NULL, 15, 7, 'NO', 'CDM-POA-PC-Form', 'A', sysdate, 0);
INSERT INTO GPYT_T025_ADJUNTO (A025CODIGO, A025NOMBRADJNT, A025DESCRPCNADJNT, A025IDTIPPROYCT, A025IDPANTALLA, A025APLICPCNADJNT, A025NOMFORMATO, A025ESTADOREGISTRO,  A025FECHACREACION, A025USUARIOCREACION) 
VALUES (5, 'Solicitud de Carta de No-Objeción', 'No. De radicad de la Solicitud de Carta de No-Objeción suscrita por el representante legal o quien haga sus veces (en caso de ser persona jurídica) o la persona natural interesada, con el nombre o razón social, número de identificación, domicilio y nacionalidad. (Esto en caso de que este ya haya sido entregado al Ministerio de Ambiente y Desarrollo Sostenible).', 14, 8, 'SI', NULL, 'A', sysdate, 0);
INSERT INTO GPYT_T025_ADJUNTO (A025CODIGO, A025NOMBRADJNT, A025DESCRPCNADJNT, A025IDTIPPROYCT, A025IDPANTALLA, A025APLICPCNADJNT, A025NOMFORMATO, A025ESTADOREGISTRO,  A025FECHACREACION, A025USUARIOCREACION) 
VALUES (6, 'Formato de Identificación del Proyecto', 'Adjuntar Anexo 3. “Formato de Identificación del Proyecto” debidamente diligenciado de la Resolución 2734 de 2010', 14, 8, 'NO', NULL, 'A', sysdate, 0);
INSERT INTO GPYT_T025_ADJUNTO (A025CODIGO, A025NOMBRADJNT, A025DESCRPCNADJNT, A025IDTIPPROYCT, A025IDPANTALLA, A025APLICPCNADJNT, A025NOMFORMATO, A025ESTADOREGISTRO,  A025FECHACREACION, A025USUARIOCREACION) 
VALUES (7, 'Solicitud de Carta de No-Objeción', 'No. De radicado de la Solicitud de Carta de No Objeción del POA suscrita por el representante legal de la Entidad Coordinadora, o quien haga sus veces (en caso de ser persona jurídica) o la persona natural interesada, con el nombre o razón social, número de identificación, domicilio y nacionalidad. Esto en caso de que este ya haya sido entregado al Ministerio de Ambiente y Desarrollo Sostenible.', 15, 8, 'SI', NULL, 'A', sysdate, 0);
INSERT INTO GPYT_T025_ADJUNTO (A025CODIGO, A025NOMBRADJNT, A025DESCRPCNADJNT, A025IDTIPPROYCT, A025IDPANTALLA, A025APLICPCNADJNT, A025NOMFORMATO, A025ESTADOREGISTRO,  A025FECHACREACION, A025USUARIOCREACION) 
VALUES (8, 'Formato de Identificación del Proyecto', 'Anexo 3. “Formato de Identificación del Proyecto” debidamente diligenciado de la Resolución 2733 de 2010', 15, 8, 'NO', NULL, 'A', sysdate, 0);
INSERT INTO GPYT_T025_ADJUNTO (A025CODIGO, A025NOMBRADJNT, A025DESCRPCNADJNT, A025IDTIPPROYCT, A025IDPANTALLA, A025APLICPCNADJNT, A025NOMFORMATO, A025ESTADOREGISTRO,  A025FECHACREACION, A025USUARIOCREACION) 
VALUES (9, 'Solicitud de Autorizacion Entidad Coordinadora', 'No. De radicado de la Solicitud de Autorización de Entidad Coordinadora del POA suscrita por el representante legal de la Entidad Coordinadora, o quien haga sus veces (en caso de ser persona jurídica) o la persona natural interesada, con el nombre o razón social, número de identificación, domicilio y nacionalidad: Esto en caso de que este ya haya sido entregado al Ministerio de Ambiente y Desarrollo Sostenible).', 15, 9, 'SI', NULL, 'A', sysdate, 0);
INSERT INTO GPYT_T025_ADJUNTO (A025CODIGO, A025NOMBRADJNT, A025DESCRPCNADJNT, A025IDTIPPROYCT, A025IDPANTALLA, A025APLICPCNADJNT, A025NOMFORMATO, A025ESTADOREGISTRO,  A025FECHACREACION, A025USUARIOCREACION) 
VALUES (10, 'Formato mecanismo de desarrollo limpio', 'Formato 1: Formato de solicitud de autorización de coordinación de un programa de actividades bajo el mecanismo de desarrollo limpio, del Anexo 1 de la Resolución 2733 de 2010.', 15, 9, 'NO', NULL, 'A', sysdate, 0);
INSERT INTO GPYT_T025_ADJUNTO (A025CODIGO, A025NOMBRADJNT, A025DESCRPCNADJNT, A025IDTIPPROYCT, A025IDPANTALLA, A025APLICPCNADJNT, A025NOMFORMATO, A025ESTADOREGISTRO,  A025FECHACREACION, A025USUARIOCREACION) 
VALUES (11, 'Certificado de existencia y representación legal', 'Copia del certificado de existencia y representación legal de la Entidad Coordinadora expedido por la Cámara de Comercio. En caso de personas jurídicas extranjeras, los documentos que acrediten su existencia y representación legal, deberán estar autenticados o apostillados por el funcionario consular o quien haga sus veces, y en idioma castellano. En el caso de personas jurídicas de derecho público colombiano se acreditará aportando la norma de creación de la misma, copia de los estatutos cuando a ello hubiere lugar y del acto administrativo de nombramiento del representante legal de la Entidad.', 15, 9, 'NO', NULL, 'A', sysdate, 0);
INSERT INTO GPYT_T025_ADJUNTO (A025CODIGO, A025NOMBRADJNT, A025DESCRPCNADJNT, A025IDTIPPROYCT, A025IDPANTALLA, A025APLICPCNADJNT, A025NOMFORMATO, A025ESTADOREGISTRO,  A025FECHACREACION, A025USUARIOCREACION) 
VALUES (12, 'Formato de cumplimiento de toda la normatividad sectorial y ambiental', 'Formato 2 Anexo 1 “Declaración de cumplimiento de toda la normatividad sectorial y ambiental” de la Resolución 2733 de 2010 debidamente diligenciado.', 15, 9, 'NO', NULL, 'A', sysdate, 0);
INSERT INTO GPYT_T025_ADJUNTO (A025CODIGO, A025NOMBRADJNT, A025DESCRPCNADJNT, A025IDTIPPROYCT, A025IDPANTALLA, A025APLICPCNADJNT, A025NOMFORMATO, A025ESTADOREGISTRO,  A025FECHACREACION, A025USUARIOCREACION) 
VALUES (13, 'Información sobre el valor monetario y la distribución de los CERs', 'Formato 3 Anexo 1 “Declaración de información sobre el valor monetario y la distribución de los CERs” de la Resolución 2733 de 2010 debidamente diligenciado.', 15, 9, 'NO', NULL, 'A', sysdate, 0);
INSERT INTO GPYT_T025_ADJUNTO (A025CODIGO, A025NOMBRADJNT, A025DESCRPCNADJNT, A025IDTIPPROYCT, A025IDPANTALLA, A025APLICPCNADJNT, A025NOMFORMATO, A025ESTADOREGISTRO,  A025FECHACREACION, A025USUARIOCREACION) 
VALUES (14, 'Declaración de responsabilidad de coordinación ', 'Formato 4 Anexo 1 “Declaración de responsabilidad de coordinación durante el tiempo de duración del POA” de la Resolución 2733 de 2010 debidamente diligenciado.', 15, 9, 'NO', NULL, 'A', sysdate, 0);

COMMIT;