--------------------------------------------------------
-- Archivo creado  - domingo-diciembre-25-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View GPYV_009_POLITICAPROYECTO
--------------------------------------------------------
 CREATE OR REPLACE FORCE VIEW "GPYV_009_POLITICAPROYECTO" ("A007CODIGO", "A007IDPROYECTO", "A007IDPOLITICA", "A003NIVEL4", "A003NOMNIVEL4", "A026CODIGO", "A026DESCRPCNARCHIV", "A026NOMARCHIVO", "A026HASHARCHIVO", "A026ESTADOREGISTRO") AS 
  SELECT PP.A007CODIGO,
    PP.A007IDPROYECTO,
    PP.A007IDPOLITICA,
    PROY.A003NIVEL4,
    PROY.A003NOMNIVEL4,
    AR.A026CODIGO,
    AR.A026DESCRPCNARCHIV,
    AR.A026NOMARCHIVO,
    AR.A026HASHARCHIVO,
    AR.A026ESTADOREGISTRO
  FROM GPYT_T007_PROY_POLITICA PP
  LEFT JOIN GPYT_T003_POLITICA PROY
  ON PP.A007IDPOLITICA = PROY.A003CODIGO
  LEFT JOIN GPYT_T026_ARCHIVO AR
  ON PROY.A003IDARCHIV =AR.A026CODIGO
  ORDER BY A003NIVEL4 ASC;
REM INSERTING into GESTOR.GPYV_009_POLITICAPROYECTO
SET DEFINE OFF;
