PROCEDURE Pr_ActualizarCostos(
    p_A002CODIGO            IN GPYT_T002_PROYECTO.A002CODIGO%TYPE,
    p_A002COSTSESTMDTOTL    IN GPYT_T002_PROYECTO.A002COSTSESTMDTOTL%TYPE,
    p_A002COSTSESTMDFORMLCN IN GPYT_T002_PROYECTO.A002COSTSESTMDFORMLCN%TYPE,
    p_A002COSTTONLDRDCR     IN GPYT_T002_PROYECTO.A002COSTTONLDRDCR%TYPE,
    p_A002TRM               IN GPYT_T002_PROYECTO.A002TRM%TYPE,
    p_A002BUSQUDFINNCCN     IN GPYT_T002_PROYECTO.A002BUSQUDFINNCCN%TYPE,
    p_idUsuario             IN NUMBER,
    p_resultado OUT CURSOR_SALIDA,
    p_codError OUT NUMBER,
    p_msjError OUT VARCHAR2);