--------------------------------------------------------
-- Archivo creado  - sábado-abril-01-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View GPYV_006_PROYECTOS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "GESTOR"."GPYV_006_PROYECTOS" ("A001CODIGO", "A001SIGLA", "A002CODIGO", "A052NOMBREENTIDAD", "A002NOMBRPROYCT", "A001NOMBRE", "TIPOPROYECTO", "A002TIPPROYCT", "A002DESCRPCINPROYCT", "IDESTADOPROYECTO", "ESTADOPROYECTO", "A002IDUSR", "A055IDPUBLICADOR", "A002ESTADOREGISTRO", "A002FECHACREACION") AS 
  SELECT A001CODIGO,
    A001SIGLA, 
    A002CODIGO,
    CASE WHEN USR_PUBLICADOR.A041IDCLASUSR = 10 THEN CONCAT (PER_GESTOR.A052APELLIDO, CONCAT(' ', COALESCE(PER_GESTOR.A052NOMBRE, ''))) ELSE CONCAT (PER_PUBLICADOR.A052APELLIDO, CONCAT(' ', COALESCE (PER_PUBLICADOR.A052NOMBRE, ''))) END A052NOMBREENTIDAD,
    A002NOMBRPROYCT,
    A001NOMBRE,
    L1.A102VALORCORTO TIPOPROYECTO,
    A002TIPPROYCT,
    A002DESCRPCINPROYCT,
	  L2.A102CODIGO IDESTADOPROYECTO,
    L2.A102VALOR ESTADOPROYECTO,
    A002IDUSR,
    A002IDUSR A055IDPUBLICADOR,    
    A002ESTADOREGISTRO,
    A002FECHACREACION
  FROM GPYT_T002_PROYECTO
    LEFT JOIN PART_T102_LISTA L1 ON L1.A102CODIGO = A002TIPPROYCT -- tipo de proyecto
    LEFT JOIN PART_T102_LISTA L2 ON L2.A102CODIGO = A002ESTADOPROYECTO
    LEFT JOIN GPYT_T041_USUARIO USR_PUBLICADOR ON A002IDUSR  = A041CODIGO
    LEFT JOIN GPYT_T052_PERSONA PER_PUBLICADOR ON USR_PUBLICADOR.A041IDPERSONA  = A052CODIGO
    LEFT JOIN GPYT_T001_ENTIDAD ON A001CODIGO   = PER_PUBLICADOR.A052IDENTIDAD
    LEFT JOIN GPYT_T041_USUARIO USR_GESTOR ON  USR_PUBLICADOR.A041USUARIOCREACION = USR_GESTOR.A041CODIGO
    LEFT JOIN GPYT_T052_PERSONA PER_GESTOR ON USR_GESTOR.A041IDPERSONA  = PER_GESTOR.A052CODIGO ;
