create or replace package PK_T997_MENSAJE_DEBUG is

  PROCEDURE Pr_Insertar(p_A997FECHAOPERACION IN SIST_T997_MENSAJE_DEBUG.A997FECHAOPERACION%TYPE,
                        p_A997USUARIO        IN SIST_T997_MENSAJE_DEBUG.A997USUARIO%TYPE,
                        p_A997PAQUETE        IN SIST_T997_MENSAJE_DEBUG.A997PAQUETE%TYPE,
                        p_A997PROCEDIMIENTO  IN SIST_T997_MENSAJE_DEBUG.A997PROCEDIMIENTO%TYPE,
                        p_A997DESCRIPCION    IN SIST_T997_MENSAJE_DEBUG.A997DESCRIPCION%TYPE,
                        p_A997NIVEL          IN SIST_T997_MENSAJE_DEBUG.A997NIVEL%TYPE,
                        p_A997CODIGO         OUT SIST_T997_MENSAJE_DEBUG.A997CODIGO%TYPE);

end Pk_T997_MENSAJE_DEBUG;