create or replace package PK_T996_AUDITORIA is

  PROCEDURE Pr_Insertar(p_A996IDOBJETO      IN SIST_T996_AUDITORIA.A996IDOBJETO%TYPE,
                        p_A996OBJETO        IN SIST_T996_AUDITORIA.A996OBJETO%TYPE,
                        p_A996OPERACION     IN SIST_T996_AUDITORIA.A996OPERACION%TYPE,
                        p_A996USUARIO       IN SIST_T996_AUDITORIA.A996USUARIO%TYPE,
                        p_A996PROCEDIMIENTO IN SIST_T996_AUDITORIA.A996PROCEDIMIENTo%TYPE,
                        p_A996PAQUETE       IN SIST_T996_AUDITORIA.A996PAQUETE%TYPE,
                        p_A996CODIGO        OUT SIST_T996_AUDITORIA.A996CODIGO%TYPE);
                        
end PK_T996_AUDITORIA;