--------------------------------------------------------
-- Archivo creado  - martes-marzo-07-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GPYT_T059_PROY_POLITICAS_P
--------------------------------------------------------

  CREATE TABLE "GESTOR"."GPYT_T059_PROY_POLITICAS_P" 
   (	"A059CODIGO" NUMBER(7,0), 
	"A059IDPROYECTO" NUMBER(7,0), 
	"A059DESCRIPCION" VARCHAR2(200 BYTE), 
	"A059ESTADOREGISTRO" CHAR(1 BYTE), 
	"A059FECHACREACION" DATE, 
	"A059FECHAMODIFICACION" DATE, 
	"A059USUARIOCREACION" NUMBER(7,0), 
	"A059USUARIOMODIFICACION" NUMBER(7,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GESTORDAT" ;
REM INSERTING into GESTOR.GPYT_T059_PROY_POLITICAS_P
SET DEFINE OFF;
Insert into GESTOR.GPYT_T059_PROY_POLITICAS_P (A059CODIGO,A059IDPROYECTO,A059DESCRIPCION,A059ESTADOREGISTRO,A059FECHACREACION,A059FECHAMODIFICACION,A059USUARIOCREACION,A059USUARIOMODIFICACION) values ('1','1','Modificado','I',to_date('07/03/17','DD/MM/RR'),to_date('07/03/17','DD/MM/RR'),'1','1');
--------------------------------------------------------
--  DDL for Index PK_T059
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOR"."PK_T059" ON "GESTOR"."GPYT_T059_PROY_POLITICAS_P" ("A059CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GESTORDAT" ;
--------------------------------------------------------
--  Constraints for Table GPYT_T059_PROY_POLITICAS_P
--------------------------------------------------------

  ALTER TABLE "GESTOR"."GPYT_T059_PROY_POLITICAS_P" ADD CONSTRAINT "PK_T059" PRIMARY KEY ("A059CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GESTORDAT"  ENABLE;
  ALTER TABLE "GESTOR"."GPYT_T059_PROY_POLITICAS_P" ADD CONSTRAINT "CK_A059ESTADOREGISTRO" CHECK ( A059ESTADOREGISTRO IN ('A', 'I')) ENABLE;
  ALTER TABLE "GESTOR"."GPYT_T059_PROY_POLITICAS_P" MODIFY ("A059USUARIOCREACION" NOT NULL ENABLE);
  ALTER TABLE "GESTOR"."GPYT_T059_PROY_POLITICAS_P" MODIFY ("A059ESTADOREGISTRO" NOT NULL ENABLE);
  ALTER TABLE "GESTOR"."GPYT_T059_PROY_POLITICAS_P" MODIFY ("A059IDPROYECTO" NOT NULL ENABLE);
  ALTER TABLE "GESTOR"."GPYT_T059_PROY_POLITICAS_P" MODIFY ("A059CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table GPYT_T059_PROY_POLITICAS_P
--------------------------------------------------------

  ALTER TABLE "GESTOR"."GPYT_T059_PROY_POLITICAS_P" ADD CONSTRAINT "FK_T059_T002" FOREIGN KEY ("A059IDPROYECTO")
	  REFERENCES "GESTOR"."GPYT_T002_PROYECTO" ("A002CODIGO") ENABLE;
